### ISSUE TITLE
How to make a checkout for a specific product?

### ISSUE THREAD

**Issue by Bewinxed** [NuroDev/lemonsqueezy.ts#12]
I tried so many variations with the api and the client, where do we specify the store id or the product id? (the product doesn't have variants)

Thanks!

**Comment by minjie0501** [comment]
All products will have at least 1 variant (check the docs: https://docs.lemonsqueezy.com/api/variants).
We have to wait for the `0.1.7` release to be able to specify the store id and variant id when creating a checkout. (https://github.com/NuroDev/lemonsqueezy.ts/issues/10)


@NuroDev ETA on the release? 😄

**Comment by NuroDev** [comment]
I was going to try & fix my CI/CD tests to get all tests fully functioning before publishing but I've not found much time to be able to do so.

In the mean time I have manually published version `0.1.7`. This should, in theory, fix these issue but I have not been able to 100% verify this. If there is still issues after this let me know & I will take another look into it.
