### ISSUE TITLE
Attributes missing on Subscription object

### ISSUE THREAD

**Issue by kisamoto** [NuroDev/lemonsqueezy.ts#27]
Some attributes are missing on the Subscription object:

* `card_brand`
* `card_last_four`

[Lemon Squeezy Docs](https://docs.lemonsqueezy.com/api/subscriptions#the-subscription-object). 

As these are [recommended to be recorded](https://docs.lemonsqueezy.com/guides/developer-guide/taking-payments#saving-checkout-and-subscription-data-in-your-database) in user database would be useful to have.

**Comment by remorses** [comment]
There is also `customer_portal`:  response['data']['attributes']['urls']['customer_portal']

Docs: https://docs.lemonsqueezy.com/guides/developer-guide/customer-portal
