### ISSUE TITLE
[HELP] - I'm getting error while importing it into the nextjs app (using v14 with pages route)

### ISSUE THREAD

**Issue by rohitdasu** [NuroDev/lemonsqueezy.ts#32]
It says "async_hooks" not found. i installed it manually but no luck. am i doing anything wrong? please guide me here. thanks

Screenshot:

<img width="1440" alt="Screenshot 2024-01-01 at 6 33 28 PM" src="https://github.com/NuroDev/lemonsqueezy.ts/assets/48400770/d9b2ec68-6716-4884-a045-4c13cc998258">

**Comment by rohitdasu** [comment]
my bad i was creating its object at wrong place.

**Comment by Temitope-Emmanuel** [comment]
What did you do to fix it @rohitdasu , I'm having the same issue
