### ISSUE TITLE
TypeErrr

### ISSUE THREAD

**Issue by hassan-jahan** [NuroDev/lemonsqueezy.ts#7]
Hi,
I constantly get this error using provided sample usage.

```
TypeError: (0 , B.fetch) is not a function
    at requestLemonSqueeze (/Users/hassan/work/minoo/node_modules/lemonsqueezy.ts/src/shared/shared.actions.ts:44:28)
    at getUser (/Users/hassan/work/minoo/node_modules/lemonsqueezy.ts/src/modules/user/user.action.ts:20:10)
```

**Comment by NuroDev** [comment]
Hey, can I ask for some extra detail about you are using to run the sample usage:
	- Engine (Node.js, Deno, etc)
	- Engine version (Node.js v19.6.0)
	-

**Comment by hassan-jahan** [comment]
Sure, it's Mode 14.21

**Comment by NuroDev** [comment]
Ah, that would be why then. Currently Node.js 14 is not currently supported. Can you try running this using a newer version of Node.js, preferably the LTS version which is currently `18.15.0`.

If this does fix the issue I will add a fix to the `package.json` to pin a minimum Node.js version

**Comment by hassan-jahan** [comment]
Right, it seems fetch function is pretty new. Now works perfectly with Node 18!

Thanks for the quick reply.
