### ISSUE TITLE
Allow optional `checkout_data`, `checkout_options`, & `product_options` field keys.

### ISSUE THREAD

**Issue by kaleabmelkie** [NuroDev/lemonsqueezy.ts#8]
Currently, all the fields of `LemonsqueezyCheckoutData`, `LemonsqueezyCheckoutOptions`, & `LemonsqueezyProductOptions` are required in TypeScript.

When calling `createCheckout`, we get a type error unless all the fields are provided for these objects:

<img width="656" alt="Screenshot 2023-03-20 at 1 04 36 PM" src="https://user-images.githubusercontent.com/29814842/226308362-9afb627d-ae58-4aa7-9ed6-8eb0861093f1.png">

I believe the fix should be as simple as making the fields of the three type above optional, right?

I made them optional in my local node_modules folder and it seemed to work (locally). I'm just not sure if any of these fields need to be required (not optional):

<img width="656" alt="Screenshot 2023-03-20 at 1 11 09 PM" src="https://user-images.githubusercontent.com/29814842/226309595-ab066181-6fb0-4d23-9d86-d1c05cfb310c.png">

**Comment by NuroDev** [comment]
Changes for this had already been made recently to improve this but weren't perfect.

I have just pushed [a new change](https://github.com/NuroDev/lemonsqueezy.ts/commit/8da30f678d35f6bb44fa1b2e636ab91109046d7f) that should fix this.

I will publish a new version with correctly functioning create checkout logic soon.

**Comment by kaleabmelkie** [comment]
Alright, thanks!
